### ISSUE TITLE
Docker Hub integration trigger event

### ISSUE THREAD

**Issue by FabrizioSandri** [FabrizioSandri/RcppDeepState-action#11]
Hi @randy3k, following [your recommendation](https://github.com/FabrizioSandri/RcppDeepState-action/pull/4#issuecomment-1183670955) to integrate my action with Docker Hub, the overall execution time of the action has been reduced from an average of 30 minutes to less than 10 minutes. This is a significant improvement; thank you for pointing it out to me. 

However, an issue arises with this architecture: I need to specify the event that should trigger the [workflow that builds and pushes the image to Docker Hub](https://github.com/FabrizioSandri/RcppDeepState-action/blob/main/.github/workflows/docker-push.yaml). Currently, the image on Docker Hub is updated whenever the `docker` folder is changed.
```yaml
on:
  push:
    paths:
      - 'docker/**'
```

The issue with this method is that if I open a pull request to add some new changes, the image will be updated and all repositories that use my GitHub action will actually run the changes in my pull request. 
This is motivated by this line in the `action.yaml` file:
```yaml
- name: Analyze the package with RcppDeepState 
      id: rcppdeepstate
      uses: docker://fabriziosandri/rcppdeepstate:latest
```

I was wondering if using Docker Hub's tagging mechanism could be a solution to this problem.
So, if I make modifications within a pull request, the image will be pushed with a new tag rather than the usual `latest` tag. 

Do you think this can be a valid option? or maybe should I do something different?

**Comment by randy3k** [comment]
Definitely, you would want to tag `docker://fabriziosandri/rcppdeepstate` with different versions, e.g, latest, stable, devel, v1 etc.

Unfortunately, I don't think the `uses` field supports `inputs` like this.
```
    - name: Analyze the package with RcppDeepState 
      id: rcppdeepstate
      uses: docker://fabriziosandri/rcppdeepstate:${{ inputs.docker_image_tag }}
      with:
        fail_ci_if_error: ${{ inputs.fail_ci_if_error }}
        location: ${{ inputs.location }}
        seed: ${{ inputs.seed }}
        time_limit: ${{ inputs.time_limit }}
        max_inputs: ${{ inputs.max_inputs }}
        verbose: ${{ inputs.verbose }}
```

You may need to reorganize your actions, so that consumers would need to specify the docker image explicitly. For example, like this,

```
jobs:
  RcppDeepState:
    runs-on: ubuntu-latest
    container:
       image:fabriziosandri/rcppdeepstate:stable
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:      
      - uses: actions/checkout@v2 

      - uses:  FabrizioSandri/RcppDeepState-action@stable
        with:
          location: '/inst/testpkgs/testSAN'
          comment: 'true'
```

**Comment by FabrizioSandri** [comment]
@randy3k Thank you for your advice; I used different tags like `latest` and `devel` as you suggested.

As you pointed out, expressions cannot be used within the `uses` field. However, to face this problem, I came up with a solution: build and push the image with a specific tag, defined by the branch where the push events occurs:
```yaml
- name: Build and push
  uses: docker/build-push-action@v3
  with:
    context: ./docker
    push: true
    tags: fabriziosandri/rcppdeepstate:${{ github.ref_name == 'main' && 'latest' || 'devel' }}
```
When I make any changes within a pull request the `latest` image is not updated; instead, the new image is uploaded with the `devel` tag. On the other side, when the workflow is triggered by a push event on the `main` branch, the `latest` tag is used.


Due to the lack of expression support in the `uses` field, I decided to add an extra step to the workflow used for testing: after checking out the Action's repository, the 'acion.yml' file is updated locally inside the Action's runner by replacing the `uses: docker://fabriziosandri/rcppdeepstate:latest` line with `uses: docker://fabriziosandri/rcppdeepstate:devel` using the `sed` command. As a result, I am certain that the tests will be run on the `devel` image.

```yaml
on:
  pull_request:
    branches: 
      - '*'

name: "Check testSAN package"

jobs:
  RcppDeepState:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:      
      - uses: actions/checkout@v2 

      - name: Switch to test image
        run: |
          sed -i "s/fabriziosandri\/rcppdeepstate:latest/fabriziosandri\/rcppdeepstate:devel/g" action.yml
        shell: bash

      - name: Analyze the package with RcppDeepState  # run RccpDeepState on 'testSAN'
        uses: ./
        with:
          location: /tests/testSAN
          fail_ci_if_error: 'false'
          comment: 'true'
```

The user will not be affected by this change because he will always use the action with the `latest` image.

Issue solved with pull request #12
