### ISSUE TITLE
parameter names / value?

### ISSUE THREAD

**Issue by tdhock** [FabrizioSandri/RcppDeepState-action#16]
Are single quotes required for values in yaml? Would be nice to remove them. Also can we change time_limit to time_limit_seconds for clarity? like below
```
      - uses: FabrizioSandri/RcppDeepState-action@main
        with:
          fail_ci_if_error: true
          seed: 5
          time_limit_seconds: 60
          max_inputs: 100
          comment: true
          verbose: true
```
